version: "3.7"

volumes:
    expansion_recorder:    
       name: expansion_recorder
 
services:
   db:
       container_name: exp_database
       image: postgres:9.6.17-alpine
       environment:
         - "POSTGRES_HOST_AUTH_METHOD=trust"
       
       ports:
        - "5432:5432"
       volumes:
        - expansion_recorder:/var/lib/postgresql/data 
        - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh