db:
    container_name: exp_database
    image: postgres:9.6.17-alpine
    ports:
     - "5432:5432"
    volumes:
     - expansion_recorder:/var/lib/postgresql/data
     - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh